base_url_value = 'https://demoqa.com'
profile_page_url = 'https://demoqa.com/profile'
login_page_url = 'https://demoqa.com/login'
user_name = '1'
user_password = 'A_1234567890a!'
login_page_error_message = 'Invalid username or password!'